version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    networks:
      - kafka-demo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.4.3
    networks:
      - kafka-demo
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:9092,LOCAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,LOCAL:PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  kafka-demo:
    name: kafka-demo
